# -*- Mode: YAML; indent-tabs-mode: nil; tab-width: 2 -*-

name: dwarffortress
version: 0.47.01
summary: Dwarf Fortress world simulator. Forked from 'https://github.com/mikix/df'.
description: |
  Dwarf Fortress is a single-player fantasy game by Bay 12 Games. You can control a dwarven outpost or an adventurer in a randomly generated, persistent world.

  This is an unofficial snap, which redistributes the original binaries without modification. This version is forked from 'https://github.com/mikix/df'.

  Upstream: http://www.bay12games.com/dwarves/
confinement: strict
grade: stable
architectures: [amd64]

parts:
  tarball:
    plugin: dump
    source: http://www.bay12games.com/dwarves/df_47_01_linux.tar.bz2
    source-checksum: sha512/72745e5f22c76592ac04051550714d91609f7428e733c3872fcb2a6d97f4adb9760bd6fafa87051aef0d58a5ba7c5e7f1feee9ed02933e4fd7320dca1bc73e57
    override-build: |
      chmod a+x df
      find . -type d -exec chmod a+rx {} +
      snapcraftctl build
    prime:
      - -g_src
      - -libs/libstdc++.so.6
  desktop-gtk2:
    after: []
  deps:
    plugin: nil
    stage-packages:
      - freeglut3
      - libglu1-mesa
      - libopenal1
      - libsdl-image1.2
      - libsdl-ttf2.0-0
  overlay:
    plugin: dump
    source: overlay

apps:
  dwarffortress:
    command: desktop-launch $SNAP/wrapper.sh
    plugs: [opengl, pulseaudio, x11, unity7]
