# -*- Mode: YAML; indent-tabs-mode: nil; tab-width: 2 -*-

name: dwarf-fortress
version: 0.44.10
summary: Dwarf Fortress world simulator
description: |
  Dwarf Fortress is a single-player fantasy game by Bay 12 Games. You can control a dwarven outpost or an adventurer in a randomly generated, persistent world.
  
  This is an unofficial snap, which redistributes the original binaries without modification.
  
  Upstream: http://www.bay12games.com/dwarves/
confinement: strict
grade: stable
architectures: [amd64]

parts:
  tarball:
    plugin: dump
    source: http://www.bay12games.com/dwarves/df_44_10_linux.tar.bz2
    source-checksum: sha512/a75cc30868f182c375825966438d455e57d244f5277b3f94a3745a992703578d9e971335f9d5f1d077f89d43ed7d70bc5d36f6608d9a1625d4a3494095001721
    override-build: |
      chmod a+x df
      find . -type d -exec chmod a+rx {} +
      snapcraftctl build
    prime:
      - -g_src
      - -libs/libstdc++.so.6
  desktop-gtk2:
    after: [] # just so the remote part gets defined
  deps:
    plugin: nil
    stage-packages:
      - freeglut3
      - libglu1-mesa
      - libopenal1
      - libsdl-image1.2
      - libsdl-ttf2.0-0
  overlay:
    plugin: dump
    source: overlay

apps:
  dwarf-fortress:
    command: desktop-launch $SNAP/wrapper
    plugs: [opengl, pulseaudio, x11, unity7]
